const esc=v=>String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");
const fmt=v=>{if(!v)return"—";const d=new Date(v);return Number.isNaN(d.getTime())?String(v):new Intl.DateTimeFormat("en-US",{month:"short",day:"numeric",hour:"numeric",minute:"2-digit"}).format(d)};
const title=v=>String(v||"run").replaceAll("_"," ").replace(/\b\w/g,m=>m.toUpperCase());

async function api(url,options={}){const r=await fetch(url,{cache:"no-store",...options,headers:{accept:"application/json",...(options.headers||{})}});const data=await r.json().catch(()=>({}));if(!r.ok){const e=new Error(data.error||`${r.status}`);e.status=r.status;throw e}return data}
function token(){let value=sessionStorage.getItem("paydirt-admin-token")||"";if(!value){value=window.prompt("Paydirt admin token")||"";if(value)sessionStorage.setItem("paydirt-admin-token",value)}return value}
async function post(url,body={}){const t=token();if(!t)throw new Error("Admin token required");return api(url,{method:"POST",headers:{"content-type":"application/json",authorization:`Bearer ${t}`},body:JSON.stringify(body)})}

function ensurePanel(){const command=document.querySelector("#view-command");if(!command||document.querySelector("#workflow-ops"))return;const inbox=command.querySelector(".inbox-preview");const panel=document.createElement("section");panel.id="workflow-ops";panel.className="panel workflow-ops";panel.innerHTML=`<div class="panel-head"><div><p class="eyebrow">DURABLE ORCHESTRATION</p><h2>Workflow operations</h2></div><div class="workflow-actions"><span id="workflow-flash" class="workflow-flash"></span><button id="run-discovery" class="workflow-button">RUN DISCOVERY NOW</button></div></div><div class="workflow-grid"><div class="workflow-column"><h3>RUNS</h3><div id="workflow-runs"></div></div><div class="workflow-column"><h3>SOURCE HEALTH</h3><div id="source-health"></div></div></div>`;command.insertBefore(panel,inbox);document.querySelector("#run-discovery")?.addEventListener("click",runDiscovery)}

function runSummary(r){const s=r.summary||{};if(r.error)return r.error;if(r.run_type==="discovery"){const bits=[];if(Number.isFinite(s.newLeads))bits.push(`${s.newLeads} new leads`);if(Number.isFinite(s.candidateEvents))bits.push(`${s.candidateEvents} candidates`);if(Number.isFinite(s.sourcesSucceeded))bits.push(`${s.sourcesSucceeded} sources`);return bits.join(" · ")||r.trigger_source||"discovery"}if(r.run_type==="validation"){const bits=[];if(s.composite!=null)bits.push(`score ${s.composite}`);if(s.recommendation)bits.push(String(s.recommendation).replaceAll("_"," "));if(s.confidence!=null)bits.push(`confidence ${Math.round(Number(s.confidence)*100)}%`);return bits.join(" · ")||r.trigger_source||"validation"}return r.trigger_source||""}

async function refresh(){ensurePanel();const panel=document.querySelector("#workflow-ops");if(!panel)return;try{const [runsData,sourcesData]=await Promise.all([api("/api/runs"),api("/api/sources")]);const runs=(runsData.runs||[]).filter(r=>["discovery","validation"].includes(r.run_type)).slice(0,10);const sources=(sourcesData.sources||[]).slice(0,12);const runsEl=document.querySelector("#workflow-runs"),sourcesEl=document.querySelector("#source-health");if(runsEl)runsEl.innerHTML=runs.map(r=>`<div class="workflow-run"><div class="workflow-run-top"><strong>${esc(title(r.run_type))}${r.opportunity_id?" / OPPORTUNITY":""}</strong><span class="workflow-status" data-status="${esc(String(r.status||"unknown").toLowerCase())}">${esc(String(r.status||"unknown").toUpperCase())}</span></div><small>${esc(fmt(r.started_at||r.created_at))} · ${esc(r.trigger_source||"workflow")}</small><small class="workflow-summary">${esc(runSummary(r)||"No summary yet")}</small></div>`).join("")||'<div class="empty">No workflow runs yet.</div>';if(sourcesEl)sourcesEl.innerHTML=sources.map(s=>`<div class="source-health"><div class="source-health-top"><strong><i class="health-dot" data-health="${esc(s.health_status||"unknown")}"></i>${esc(s.name)}</strong><span class="workflow-status">${esc(String(s.health_status||"unknown").toUpperCase())}</span></div><small>${esc(s.kind||"source")} · ${esc(fmt(s.last_scanned_at||s.updated_at))}</small>${s.last_error?`<small>${esc(s.last_error)}</small>`:""}</div>`).join("")||'<div class="empty">No source health recorded yet.</div>'}catch{panel.hidden=true}}

async function runDiscovery(){const button=document.querySelector("#run-discovery"),flash=document.querySelector("#workflow-flash");if(!button)return;button.disabled=true;if(flash){flash.className="workflow-flash";flash.textContent="QUEUEING…"}try{const out=await post("/api/workflows/discovery",{lookback_days:30});if(flash)flash.textContent=`QUEUED ${out.workflow_instance_id}`;setTimeout(refresh,800)}catch(e){if(flash){flash.className="workflow-flash error";flash.textContent=e.message}}finally{button.disabled=false}}

function selectedOpportunityId(){const hash=location.hash;const content=document.querySelector("#workspace-content");if(!content||content.hidden)return null;const candidates=[...document.querySelectorAll("[data-open]")];const active=candidates.find(x=>x.closest(".view.active"));if(active?.dataset.open)return active.dataset.open;const workspaceTitle=content.querySelector("h1")?.textContent?.trim();if(!workspaceTitle)return null;return window.__paydirtWorkflowSelectedId||null}

function installRevalidate(){const panel=document.querySelector("#workspace-content .decision-actions");if(!panel||panel.querySelector(".revalidate-button"))return;const titleText=document.querySelector("#workspace-content h1")?.textContent?.trim();if(!titleText)return;const button=document.createElement("button");button.className="action-button revalidate-button";button.textContent="REVALIDATE EVIDENCE";button.addEventListener("click",async()=>{try{const list=await api("/api/opportunities");const opp=(list.opportunities||[]).find(o=>o.name===titleText);if(!opp)throw new Error("Opportunity ID not found");button.disabled=true;button.textContent="QUEUEING…";await post(`/api/opportunities/${encodeURIComponent(opp.id)}/validate`);button.textContent="VALIDATION QUEUED";setTimeout(()=>{button.textContent="REVALIDATE EVIDENCE";button.disabled=false;refresh()},1200)}catch(e){button.textContent=`ERROR: ${e.message}`;setTimeout(()=>{button.textContent="REVALIDATE EVIDENCE";button.disabled=false},2200)}});panel.appendChild(button)}

ensurePanel();refresh();setInterval(()=>{if(document.visibilityState==="visible")refresh()},15000);new MutationObserver(()=>{ensurePanel();installRevalidate()}).observe(document.body,{subtree:true,childList:true});
